name: Auto Issue Response

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  auto-response:
    runs-on: ubuntu-latest
    steps:
      - name: Respond to new issue
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          REPO="${{ github.repository }}"
          OWNER="${{ github.repository_owner }}"
          REPO_NAME="${REPO#*/}"
          TITLE="${{ github.event.issue.title }}"
          
          RESPONSE_BODY="Thank you for opening this issue ($TITLE) 
          Our team will review it as soon as possible!"

          JSON_PAYLOAD=$(jq -n --arg body "$RESPONSE_BODY" '{"body": $body}')

          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/$OWNER/$REPO_NAME/issues/$ISSUE_NUMBER/comments" \
            -d "$JSON_PAYLOAD"
