name: Auto Issue Response

on:
  issues:
    types: [opened]

# Explicitly define the permissions needed for this workflow
permissions:
  issues: write

jobs:
  auto-response:
    runs-on: ubuntu-latest
    steps:
      - name: Respond to new issue
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          REPO="${{ github.repository }}"
          OWNER="${{ github.repository_owner }}"
          REPO_NAME="${REPO#*/}"
          
          RESPONSE_BODY="Thank you for opening this issue! Our team will review it as soon as possible. In the meantime, please make sure you have provided all necessary information, including:

          - A clear description of the problem or feature request
          - Steps to reproduce (if applicable)
          - Expected behavior
          - Actual behavior
          - Any relevant logs or error messages

          We appreciate your contribution to improving our project!"

          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$OWNER/$REPO_NAME/issues/$ISSUE_NUMBER/comments" \
            -d "{\"body\":\"$RESPONSE_BODY\"}"

      - name: Output debug information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Repository: ${{ github.repository }}"
          echo "Repository owner: ${{ github.repository_owner }}"
