name: Auto Issue Response

on:
  issues:
    types: [opened]

jobs:
  auto-response:
    runs-on: ubuntu-latest
    steps:
      - name: Respond to new issue
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          TITLE="${{ github.event.issue.title }}"
          
          gh issue comment "${{ github.event.issue.number }}" --repo "${{ github.repository }}" --body "Thank you for opening this issue ($TITLE). Our team will review it as soon as possible. In the meantime, please make sure you have provided all necessary information, including:

          - A clear description of the problem or feature request
          - Steps to reproduce (if applicable)
          - Expected behavior
          - Actual behavior
          - Any relevant logs or error messages

          We appreciate your contribution to improving our project!"
